# dnsmasq.
version: '3'
services:
  dnsmasq:
#    image: jpillora/dnsmasq
    build: .
    ports:
      - '53:53/udp'
#      - '53:53/tcp'
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./dnsmasq.conf:/etc/dnsmasq.conf
#    environment:
    restart: always
