# Syncthing Sync.
version: '3'
services:
  syncthingd:
    image: syncthing/syncthing:1.17
#    image: ghcr.io/linuxserver/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
#      - /etc/localtime:/etc/localtime
      - ./syncdata:/var/syncthing
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Asia/Shanghai
    container_name: syncthingd
    restart: unless-stopped
#    restart: always
